* county-heatmap-generator
The code in this repo is can be used to generate heatmaps using the plotpy
library. The "heat" in this case it the number of mentions of each county within
several media formats.
** 1. Environment Setup
*** 1.1. Get the datafiles
I will not provide these for you. But they are data files which contain county
fips codes and names. I count the number of entries to get the hits which this
heatmap uses as it's Z dimension.
*** 1.2. Environment setup
These steps assume a linux system.
*** 1.3. Clone the repository
git@github.com:jguzman-tech/county-heatmap-generator.git
*** 1.4. Create an arbitrary directory
#+BEGIN_SRC
mkdir ./.venv
#+END_SRC
*** 1.5. Activate the virtual environment
#+BEGIN_SRC
. ./.venv/bin/activate
#+END_SRC
**** 1.5.1 You can use an easy to remember bash alias to activate the venv
***** 1.5.1.1 Open your ~/.bashrc
#+BEGIN_SRC
vim ~/.bashrc
#+END_SRC
***** 1.5.1.2 Add this line to your ~/.bashrc
#+BEGIN_SRC
alias act=". ./.venv/bin/activate"
#+END_SRC
You can replace act with any valid bash identifier you want.
***** 1.5.1.3 Now reload your ~/.bashrc
#+BEGIN_SRC
source ~/.bashrc
#+END_SRC
***** 1.5.1.4 Now you can use the "act" command
#+BEGIN_SRC
act
#+END_SRC
This will be saved on all future shells sessions for your current user.
*** 1.6. Install module requirements
#+BEGIN_SRC
pip3 install -r ./requirements.txt
#+END_SRC
** 2. Execution
TBD
** 3. Reproduce results
TBD
